version: "2"
services:

  anchor-loans-mongo:
    container_name: anchor-loans-mongo
    image: "mongo:3.0.2"
    ports:
      - "27019:27017"   
    command: mongod --port 27017
    networks:
      - anchor-loans_net

  anchor-loans-front:
    image: nginx:alpine
    container_name: anchor-loans-front
    working_dir: /wedding-gallery-front
    restart: always
    volumes:
      - ./wedding-gallery-front/www:/application
      - ./docker/front/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "80:80"
    networks:
      - anchor-loans_net

  anchor-loans-site:
    build: docker/site
    container_name: anchor-loans-site
    environment:
      - AWS_ACCESS_KEY_ID=AWS_ACCESS_KEY_ID
      - AWS_SECRET_ACCESS_KEY=AWS_ACCESS_KEY_ID
    ports:
      - "8001:80"
    volumes:
      - ./wedding-gallery:/wedding-gallery
    working_dir: /wedding-gallery
    depends_on:
      - anchor-loans-mongo
    links:
      - anchor-loans-mongo
    networks:
      - anchor-loans_net

networks:
  anchor-loans_net:

    